name: Setup LibreOffice Windows
description: Setups LibreOffice on Windows

runs:
  using: composite
  steps:
    - name: Install winget
      uses: Cyberboss/install-winget@v1

    - name: Install LibreOffice
      run: winget install --id=TheDocumentFoundation.LibreOffice -e --accept-package-agreements --accept-source-agreements
      shell: pwsh
