name: Test with NodeJS
description: Tests package with NodeJS

runs:
  using: composite
  steps:
    - name: Install dependencies
      run: yarn install --frozen-lockfile --non-interactive --ignore-engines
      shell: bash

    - name: Build package
      run: yarn build
      shell: bash

    - name: Test package
      run: yarn test --maxWorkers=1
      shell: bash
