name: Setup LibreOffice Linux
description: Setups LibreOffice on Linux

runs:
  using: composite
  steps:
    - name: Install LibreOffice
      run: sudo add-apt-repository --yes ppa:libreoffice && sudo apt update && sudo apt install libreoffice -y
      shell: bash

    - name: Print LibreOffice version
      run: soffice --version
      shell: bash
