name: Setup LibreOffice Linux
description: Setups LibreOffice on Linux

runs:
  using: composite
  steps:
    - name: Install LibreOffice
      run: sudo apt update && sudo apt install libreoffice -y
      shell: bash
