name: Setup LibreOffice
description: Setups LibreOffice

runs:
  using: composite
  steps:
    - name: Install LibreOffice
      run: sudo apt update && sudo apt install libreoffice -y
      shell: bash
