name: libreoffice-file-converter publish

on:
  push:
    tags:
      - '*'

jobs:
  test:
    uses: ./.github/workflows/libreoffice-file-converter-base.yml

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          always-auth: true
          cache: yarn
          node-version: 18.16.*

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Build package
        run: yarn build

      - name: Publish package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
