name: Publish libreoffice-file-converter

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup LibreOffice
        uses: ./.github/actions/setup-libreoffice-linux

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 20.*

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Build package
        run: yarn build

      - name: Test package
        run: yarn test

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 20.*
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Build package
        run: yarn build

      - name: Publish package to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package to JSR
        run: npx jsr publish
