name: Test libreoffice-file-converter with Bun on Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-bun-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup LibreOffice
        uses: ./.github/actions/setup-libreoffice-windows

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.*

      - name: Test package
        uses: ./.github/actions/test-bun
