name: Test libreoffice-file-converter with Bun on Darwin

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-bun:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup LibreOffice
        uses: ./.github/actions/setup-libreoffice-darwin

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.15

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build package
        run: bun run build

      - name: Test package
        run: bun test --timeout 15000
