name: Test libreoffice-file-converter with NodeJS on Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-node-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [16.*, 18.*, 20.*, 22.*]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup LibreOffice
        uses: ./.github/actions/setup-libreoffice-windows

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: ${{ matrix.version }}

      - name: Test package
        uses: ./.github/actions/test-node
