name: Test libreoffice-file-converter with Deno on Darwin

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-deno-darwin:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup LibreOffice
        uses: ./.github/actions/setup-libreoffice-darwin

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.*

      - name: Test package
        uses: ./.github/actions/test-deno
