name: Test libreoffice-file-converter with NodeJS on Darwin

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-node:
    runs-on: macos-latest
    strategy:
      matrix:
        version: [16.*, 18.*, 20.*, 22.*]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup LibreOffice
        uses: ./.github/actions/setup-libreoffice-darwin

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive --ignore-engines

      - name: Build package
        run: yarn build

      - name: Test package
        run: yarn test
