name: Test with Deno
description: Tests package with Deno

runs:
  using: composite
  steps:
    - name: Install dependencies
      run: deno install
      shell: bash

    - name: Build package
      run: deno run build
      shell: bash

    - name: Test package
      run: deno test --allow-all --no-check
      shell: bash
